// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public interface AlternativeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gigachat.v1.Alternative)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gigachat.v1.Message message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.gigachat.v1.Message message = 1;</code>
   * @return The message.
   */
  com.sportbuddy.grpc.Message getMessage();
  /**
   * <code>.gigachat.v1.Message message = 1;</code>
   */
  com.sportbuddy.grpc.MessageOrBuilder getMessageOrBuilder();

  /**
   * <code>string finish_reason = 2;</code>
   * @return The finishReason.
   */
  java.lang.String getFinishReason();
  /**
   * <code>string finish_reason = 2;</code>
   * @return The bytes for finishReason.
   */
  com.google.protobuf.ByteString
      getFinishReasonBytes();

  /**
   * <code>int32 index = 3;</code>
   * @return The index.
   */
  int getIndex();
}
