// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

/**
 * Protobuf type {@code gigachat.v1.Alternative}
 */
public final class Alternative extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gigachat.v1.Alternative)
    AlternativeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Alternative.newBuilder() to construct.
  private Alternative(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Alternative() {
    finishReason_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Alternative();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_Alternative_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_Alternative_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sportbuddy.grpc.Alternative.class, com.sportbuddy.grpc.Alternative.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGE_FIELD_NUMBER = 1;
  private com.sportbuddy.grpc.Message message_;
  /**
   * <code>.gigachat.v1.Message message = 1;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.gigachat.v1.Message message = 1;</code>
   * @return The message.
   */
  @java.lang.Override
  public com.sportbuddy.grpc.Message getMessage() {
    return message_ == null ? com.sportbuddy.grpc.Message.getDefaultInstance() : message_;
  }
  /**
   * <code>.gigachat.v1.Message message = 1;</code>
   */
  @java.lang.Override
  public com.sportbuddy.grpc.MessageOrBuilder getMessageOrBuilder() {
    return message_ == null ? com.sportbuddy.grpc.Message.getDefaultInstance() : message_;
  }

  public static final int FINISH_REASON_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object finishReason_ = "";
  /**
   * <code>string finish_reason = 2;</code>
   * @return The finishReason.
   */
  @java.lang.Override
  public java.lang.String getFinishReason() {
    java.lang.Object ref = finishReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      finishReason_ = s;
      return s;
    }
  }
  /**
   * <code>string finish_reason = 2;</code>
   * @return The bytes for finishReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFinishReasonBytes() {
    java.lang.Object ref = finishReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      finishReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDEX_FIELD_NUMBER = 3;
  private int index_ = 0;
  /**
   * <code>int32 index = 3;</code>
   * @return The index.
   */
  @java.lang.Override
  public int getIndex() {
    return index_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMessage());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(finishReason_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, finishReason_);
    }
    if (index_ != 0) {
      output.writeInt32(3, index_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMessage());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(finishReason_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, finishReason_);
    }
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, index_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sportbuddy.grpc.Alternative)) {
      return super.equals(obj);
    }
    com.sportbuddy.grpc.Alternative other = (com.sportbuddy.grpc.Alternative) obj;

    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (!getFinishReason()
        .equals(other.getFinishReason())) return false;
    if (getIndex()
        != other.getIndex()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    hash = (37 * hash) + FINISH_REASON_FIELD_NUMBER;
    hash = (53 * hash) + getFinishReason().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sportbuddy.grpc.Alternative parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.Alternative parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.Alternative parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.Alternative parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.Alternative parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.Alternative parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.Alternative parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sportbuddy.grpc.Alternative parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sportbuddy.grpc.Alternative parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sportbuddy.grpc.Alternative parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sportbuddy.grpc.Alternative parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sportbuddy.grpc.Alternative parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sportbuddy.grpc.Alternative prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gigachat.v1.Alternative}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gigachat.v1.Alternative)
      com.sportbuddy.grpc.AlternativeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_Alternative_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_Alternative_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sportbuddy.grpc.Alternative.class, com.sportbuddy.grpc.Alternative.Builder.class);
    }

    // Construct using com.sportbuddy.grpc.Alternative.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMessageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      finishReason_ = "";
      index_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_Alternative_descriptor;
    }

    @java.lang.Override
    public com.sportbuddy.grpc.Alternative getDefaultInstanceForType() {
      return com.sportbuddy.grpc.Alternative.getDefaultInstance();
    }

    @java.lang.Override
    public com.sportbuddy.grpc.Alternative build() {
      com.sportbuddy.grpc.Alternative result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sportbuddy.grpc.Alternative buildPartial() {
      com.sportbuddy.grpc.Alternative result = new com.sportbuddy.grpc.Alternative(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sportbuddy.grpc.Alternative result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.message_ = messageBuilder_ == null
            ? message_
            : messageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.finishReason_ = finishReason_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.index_ = index_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sportbuddy.grpc.Alternative) {
        return mergeFrom((com.sportbuddy.grpc.Alternative)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sportbuddy.grpc.Alternative other) {
      if (other == com.sportbuddy.grpc.Alternative.getDefaultInstance()) return this;
      if (other.hasMessage()) {
        mergeMessage(other.getMessage());
      }
      if (!other.getFinishReason().isEmpty()) {
        finishReason_ = other.finishReason_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              finishReason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              index_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.sportbuddy.grpc.Message message_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sportbuddy.grpc.Message, com.sportbuddy.grpc.Message.Builder, com.sportbuddy.grpc.MessageOrBuilder> messageBuilder_;
    /**
     * <code>.gigachat.v1.Message message = 1;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.gigachat.v1.Message message = 1;</code>
     * @return The message.
     */
    public com.sportbuddy.grpc.Message getMessage() {
      if (messageBuilder_ == null) {
        return message_ == null ? com.sportbuddy.grpc.Message.getDefaultInstance() : message_;
      } else {
        return messageBuilder_.getMessage();
      }
    }
    /**
     * <code>.gigachat.v1.Message message = 1;</code>
     */
    public Builder setMessage(com.sportbuddy.grpc.Message value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
      } else {
        messageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.gigachat.v1.Message message = 1;</code>
     */
    public Builder setMessage(
        com.sportbuddy.grpc.Message.Builder builderForValue) {
      if (messageBuilder_ == null) {
        message_ = builderForValue.build();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.gigachat.v1.Message message = 1;</code>
     */
    public Builder mergeMessage(com.sportbuddy.grpc.Message value) {
      if (messageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          message_ != null &&
          message_ != com.sportbuddy.grpc.Message.getDefaultInstance()) {
          getMessageBuilder().mergeFrom(value);
        } else {
          message_ = value;
        }
      } else {
        messageBuilder_.mergeFrom(value);
      }
      if (message_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.gigachat.v1.Message message = 1;</code>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.gigachat.v1.Message message = 1;</code>
     */
    public com.sportbuddy.grpc.Message.Builder getMessageBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.gigachat.v1.Message message = 1;</code>
     */
    public com.sportbuddy.grpc.MessageOrBuilder getMessageOrBuilder() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        return message_ == null ?
            com.sportbuddy.grpc.Message.getDefaultInstance() : message_;
      }
    }
    /**
     * <code>.gigachat.v1.Message message = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sportbuddy.grpc.Message, com.sportbuddy.grpc.Message.Builder, com.sportbuddy.grpc.MessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sportbuddy.grpc.Message, com.sportbuddy.grpc.Message.Builder, com.sportbuddy.grpc.MessageOrBuilder>(
                getMessage(),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }

    private java.lang.Object finishReason_ = "";
    /**
     * <code>string finish_reason = 2;</code>
     * @return The finishReason.
     */
    public java.lang.String getFinishReason() {
      java.lang.Object ref = finishReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        finishReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string finish_reason = 2;</code>
     * @return The bytes for finishReason.
     */
    public com.google.protobuf.ByteString
        getFinishReasonBytes() {
      java.lang.Object ref = finishReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        finishReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string finish_reason = 2;</code>
     * @param value The finishReason to set.
     * @return This builder for chaining.
     */
    public Builder setFinishReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      finishReason_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string finish_reason = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFinishReason() {
      finishReason_ = getDefaultInstance().getFinishReason();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string finish_reason = 2;</code>
     * @param value The bytes for finishReason to set.
     * @return This builder for chaining.
     */
    public Builder setFinishReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      finishReason_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int index_ ;
    /**
     * <code>int32 index = 3;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }
    /**
     * <code>int32 index = 3;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(int value) {

      index_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 index = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      index_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gigachat.v1.Alternative)
  }

  // @@protoc_insertion_point(class_scope:gigachat.v1.Alternative)
  private static final com.sportbuddy.grpc.Alternative DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sportbuddy.grpc.Alternative();
  }

  public static com.sportbuddy.grpc.Alternative getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Alternative>
      PARSER = new com.google.protobuf.AbstractParser<Alternative>() {
    @java.lang.Override
    public Alternative parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Alternative> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Alternative> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sportbuddy.grpc.Alternative getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

