// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

/**
 * Protobuf type {@code gigachat.v1.ChatResponse}
 */
public final class ChatResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gigachat.v1.ChatResponse)
    ChatResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatResponse.newBuilder() to construct.
  private ChatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatResponse() {
    alternatives_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_ChatResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_ChatResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sportbuddy.grpc.ChatResponse.class, com.sportbuddy.grpc.ChatResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ALTERNATIVES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.sportbuddy.grpc.Alternative> alternatives_;
  /**
   * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.sportbuddy.grpc.Alternative> getAlternativesList() {
    return alternatives_;
  }
  /**
   * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.sportbuddy.grpc.AlternativeOrBuilder> 
      getAlternativesOrBuilderList() {
    return alternatives_;
  }
  /**
   * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
   */
  @java.lang.Override
  public int getAlternativesCount() {
    return alternatives_.size();
  }
  /**
   * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
   */
  @java.lang.Override
  public com.sportbuddy.grpc.Alternative getAlternatives(int index) {
    return alternatives_.get(index);
  }
  /**
   * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
   */
  @java.lang.Override
  public com.sportbuddy.grpc.AlternativeOrBuilder getAlternativesOrBuilder(
      int index) {
    return alternatives_.get(index);
  }

  public static final int USAGE_FIELD_NUMBER = 2;
  private com.sportbuddy.grpc.Usage usage_;
  /**
   * <code>.gigachat.v1.Usage usage = 2;</code>
   * @return Whether the usage field is set.
   */
  @java.lang.Override
  public boolean hasUsage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.gigachat.v1.Usage usage = 2;</code>
   * @return The usage.
   */
  @java.lang.Override
  public com.sportbuddy.grpc.Usage getUsage() {
    return usage_ == null ? com.sportbuddy.grpc.Usage.getDefaultInstance() : usage_;
  }
  /**
   * <code>.gigachat.v1.Usage usage = 2;</code>
   */
  @java.lang.Override
  public com.sportbuddy.grpc.UsageOrBuilder getUsageOrBuilder() {
    return usage_ == null ? com.sportbuddy.grpc.Usage.getDefaultInstance() : usage_;
  }

  public static final int MODEL_INFO_FIELD_NUMBER = 3;
  private com.sportbuddy.grpc.ModelInfo modelInfo_;
  /**
   * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
   * @return Whether the modelInfo field is set.
   */
  @java.lang.Override
  public boolean hasModelInfo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
   * @return The modelInfo.
   */
  @java.lang.Override
  public com.sportbuddy.grpc.ModelInfo getModelInfo() {
    return modelInfo_ == null ? com.sportbuddy.grpc.ModelInfo.getDefaultInstance() : modelInfo_;
  }
  /**
   * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
   */
  @java.lang.Override
  public com.sportbuddy.grpc.ModelInfoOrBuilder getModelInfoOrBuilder() {
    return modelInfo_ == null ? com.sportbuddy.grpc.ModelInfo.getDefaultInstance() : modelInfo_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < alternatives_.size(); i++) {
      output.writeMessage(1, alternatives_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getUsage());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getModelInfo());
    }
    if (timestamp_ != 0L) {
      output.writeInt64(4, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < alternatives_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, alternatives_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUsage());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getModelInfo());
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sportbuddy.grpc.ChatResponse)) {
      return super.equals(obj);
    }
    com.sportbuddy.grpc.ChatResponse other = (com.sportbuddy.grpc.ChatResponse) obj;

    if (!getAlternativesList()
        .equals(other.getAlternativesList())) return false;
    if (hasUsage() != other.hasUsage()) return false;
    if (hasUsage()) {
      if (!getUsage()
          .equals(other.getUsage())) return false;
    }
    if (hasModelInfo() != other.hasModelInfo()) return false;
    if (hasModelInfo()) {
      if (!getModelInfo()
          .equals(other.getModelInfo())) return false;
    }
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAlternativesCount() > 0) {
      hash = (37 * hash) + ALTERNATIVES_FIELD_NUMBER;
      hash = (53 * hash) + getAlternativesList().hashCode();
    }
    if (hasUsage()) {
      hash = (37 * hash) + USAGE_FIELD_NUMBER;
      hash = (53 * hash) + getUsage().hashCode();
    }
    if (hasModelInfo()) {
      hash = (37 * hash) + MODEL_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getModelInfo().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sportbuddy.grpc.ChatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.ChatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.ChatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.ChatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.ChatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.ChatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.ChatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sportbuddy.grpc.ChatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sportbuddy.grpc.ChatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sportbuddy.grpc.ChatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sportbuddy.grpc.ChatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sportbuddy.grpc.ChatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sportbuddy.grpc.ChatResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gigachat.v1.ChatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gigachat.v1.ChatResponse)
      com.sportbuddy.grpc.ChatResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_ChatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_ChatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sportbuddy.grpc.ChatResponse.class, com.sportbuddy.grpc.ChatResponse.Builder.class);
    }

    // Construct using com.sportbuddy.grpc.ChatResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAlternativesFieldBuilder();
        getUsageFieldBuilder();
        getModelInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (alternativesBuilder_ == null) {
        alternatives_ = java.util.Collections.emptyList();
      } else {
        alternatives_ = null;
        alternativesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      usage_ = null;
      if (usageBuilder_ != null) {
        usageBuilder_.dispose();
        usageBuilder_ = null;
      }
      modelInfo_ = null;
      if (modelInfoBuilder_ != null) {
        modelInfoBuilder_.dispose();
        modelInfoBuilder_ = null;
      }
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_ChatResponse_descriptor;
    }

    @java.lang.Override
    public com.sportbuddy.grpc.ChatResponse getDefaultInstanceForType() {
      return com.sportbuddy.grpc.ChatResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.sportbuddy.grpc.ChatResponse build() {
      com.sportbuddy.grpc.ChatResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sportbuddy.grpc.ChatResponse buildPartial() {
      com.sportbuddy.grpc.ChatResponse result = new com.sportbuddy.grpc.ChatResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.sportbuddy.grpc.ChatResponse result) {
      if (alternativesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          alternatives_ = java.util.Collections.unmodifiableList(alternatives_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.alternatives_ = alternatives_;
      } else {
        result.alternatives_ = alternativesBuilder_.build();
      }
    }

    private void buildPartial0(com.sportbuddy.grpc.ChatResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.usage_ = usageBuilder_ == null
            ? usage_
            : usageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.modelInfo_ = modelInfoBuilder_ == null
            ? modelInfo_
            : modelInfoBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timestamp_ = timestamp_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sportbuddy.grpc.ChatResponse) {
        return mergeFrom((com.sportbuddy.grpc.ChatResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sportbuddy.grpc.ChatResponse other) {
      if (other == com.sportbuddy.grpc.ChatResponse.getDefaultInstance()) return this;
      if (alternativesBuilder_ == null) {
        if (!other.alternatives_.isEmpty()) {
          if (alternatives_.isEmpty()) {
            alternatives_ = other.alternatives_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAlternativesIsMutable();
            alternatives_.addAll(other.alternatives_);
          }
          onChanged();
        }
      } else {
        if (!other.alternatives_.isEmpty()) {
          if (alternativesBuilder_.isEmpty()) {
            alternativesBuilder_.dispose();
            alternativesBuilder_ = null;
            alternatives_ = other.alternatives_;
            bitField0_ = (bitField0_ & ~0x00000001);
            alternativesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAlternativesFieldBuilder() : null;
          } else {
            alternativesBuilder_.addAllMessages(other.alternatives_);
          }
        }
      }
      if (other.hasUsage()) {
        mergeUsage(other.getUsage());
      }
      if (other.hasModelInfo()) {
        mergeModelInfo(other.getModelInfo());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.sportbuddy.grpc.Alternative m =
                  input.readMessage(
                      com.sportbuddy.grpc.Alternative.parser(),
                      extensionRegistry);
              if (alternativesBuilder_ == null) {
                ensureAlternativesIsMutable();
                alternatives_.add(m);
              } else {
                alternativesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getUsageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getModelInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.sportbuddy.grpc.Alternative> alternatives_ =
      java.util.Collections.emptyList();
    private void ensureAlternativesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        alternatives_ = new java.util.ArrayList<com.sportbuddy.grpc.Alternative>(alternatives_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sportbuddy.grpc.Alternative, com.sportbuddy.grpc.Alternative.Builder, com.sportbuddy.grpc.AlternativeOrBuilder> alternativesBuilder_;

    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public java.util.List<com.sportbuddy.grpc.Alternative> getAlternativesList() {
      if (alternativesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(alternatives_);
      } else {
        return alternativesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public int getAlternativesCount() {
      if (alternativesBuilder_ == null) {
        return alternatives_.size();
      } else {
        return alternativesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public com.sportbuddy.grpc.Alternative getAlternatives(int index) {
      if (alternativesBuilder_ == null) {
        return alternatives_.get(index);
      } else {
        return alternativesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public Builder setAlternatives(
        int index, com.sportbuddy.grpc.Alternative value) {
      if (alternativesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternativesIsMutable();
        alternatives_.set(index, value);
        onChanged();
      } else {
        alternativesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public Builder setAlternatives(
        int index, com.sportbuddy.grpc.Alternative.Builder builderForValue) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.set(index, builderForValue.build());
        onChanged();
      } else {
        alternativesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public Builder addAlternatives(com.sportbuddy.grpc.Alternative value) {
      if (alternativesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternativesIsMutable();
        alternatives_.add(value);
        onChanged();
      } else {
        alternativesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public Builder addAlternatives(
        int index, com.sportbuddy.grpc.Alternative value) {
      if (alternativesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternativesIsMutable();
        alternatives_.add(index, value);
        onChanged();
      } else {
        alternativesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public Builder addAlternatives(
        com.sportbuddy.grpc.Alternative.Builder builderForValue) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.add(builderForValue.build());
        onChanged();
      } else {
        alternativesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public Builder addAlternatives(
        int index, com.sportbuddy.grpc.Alternative.Builder builderForValue) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.add(index, builderForValue.build());
        onChanged();
      } else {
        alternativesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public Builder addAllAlternatives(
        java.lang.Iterable<? extends com.sportbuddy.grpc.Alternative> values) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, alternatives_);
        onChanged();
      } else {
        alternativesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public Builder clearAlternatives() {
      if (alternativesBuilder_ == null) {
        alternatives_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        alternativesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public Builder removeAlternatives(int index) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.remove(index);
        onChanged();
      } else {
        alternativesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public com.sportbuddy.grpc.Alternative.Builder getAlternativesBuilder(
        int index) {
      return getAlternativesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public com.sportbuddy.grpc.AlternativeOrBuilder getAlternativesOrBuilder(
        int index) {
      if (alternativesBuilder_ == null) {
        return alternatives_.get(index);  } else {
        return alternativesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public java.util.List<? extends com.sportbuddy.grpc.AlternativeOrBuilder> 
         getAlternativesOrBuilderList() {
      if (alternativesBuilder_ != null) {
        return alternativesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(alternatives_);
      }
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public com.sportbuddy.grpc.Alternative.Builder addAlternativesBuilder() {
      return getAlternativesFieldBuilder().addBuilder(
          com.sportbuddy.grpc.Alternative.getDefaultInstance());
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public com.sportbuddy.grpc.Alternative.Builder addAlternativesBuilder(
        int index) {
      return getAlternativesFieldBuilder().addBuilder(
          index, com.sportbuddy.grpc.Alternative.getDefaultInstance());
    }
    /**
     * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
     */
    public java.util.List<com.sportbuddy.grpc.Alternative.Builder> 
         getAlternativesBuilderList() {
      return getAlternativesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sportbuddy.grpc.Alternative, com.sportbuddy.grpc.Alternative.Builder, com.sportbuddy.grpc.AlternativeOrBuilder> 
        getAlternativesFieldBuilder() {
      if (alternativesBuilder_ == null) {
        alternativesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sportbuddy.grpc.Alternative, com.sportbuddy.grpc.Alternative.Builder, com.sportbuddy.grpc.AlternativeOrBuilder>(
                alternatives_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        alternatives_ = null;
      }
      return alternativesBuilder_;
    }

    private com.sportbuddy.grpc.Usage usage_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sportbuddy.grpc.Usage, com.sportbuddy.grpc.Usage.Builder, com.sportbuddy.grpc.UsageOrBuilder> usageBuilder_;
    /**
     * <code>.gigachat.v1.Usage usage = 2;</code>
     * @return Whether the usage field is set.
     */
    public boolean hasUsage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.gigachat.v1.Usage usage = 2;</code>
     * @return The usage.
     */
    public com.sportbuddy.grpc.Usage getUsage() {
      if (usageBuilder_ == null) {
        return usage_ == null ? com.sportbuddy.grpc.Usage.getDefaultInstance() : usage_;
      } else {
        return usageBuilder_.getMessage();
      }
    }
    /**
     * <code>.gigachat.v1.Usage usage = 2;</code>
     */
    public Builder setUsage(com.sportbuddy.grpc.Usage value) {
      if (usageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        usage_ = value;
      } else {
        usageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.gigachat.v1.Usage usage = 2;</code>
     */
    public Builder setUsage(
        com.sportbuddy.grpc.Usage.Builder builderForValue) {
      if (usageBuilder_ == null) {
        usage_ = builderForValue.build();
      } else {
        usageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.gigachat.v1.Usage usage = 2;</code>
     */
    public Builder mergeUsage(com.sportbuddy.grpc.Usage value) {
      if (usageBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          usage_ != null &&
          usage_ != com.sportbuddy.grpc.Usage.getDefaultInstance()) {
          getUsageBuilder().mergeFrom(value);
        } else {
          usage_ = value;
        }
      } else {
        usageBuilder_.mergeFrom(value);
      }
      if (usage_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.gigachat.v1.Usage usage = 2;</code>
     */
    public Builder clearUsage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      usage_ = null;
      if (usageBuilder_ != null) {
        usageBuilder_.dispose();
        usageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.gigachat.v1.Usage usage = 2;</code>
     */
    public com.sportbuddy.grpc.Usage.Builder getUsageBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getUsageFieldBuilder().getBuilder();
    }
    /**
     * <code>.gigachat.v1.Usage usage = 2;</code>
     */
    public com.sportbuddy.grpc.UsageOrBuilder getUsageOrBuilder() {
      if (usageBuilder_ != null) {
        return usageBuilder_.getMessageOrBuilder();
      } else {
        return usage_ == null ?
            com.sportbuddy.grpc.Usage.getDefaultInstance() : usage_;
      }
    }
    /**
     * <code>.gigachat.v1.Usage usage = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sportbuddy.grpc.Usage, com.sportbuddy.grpc.Usage.Builder, com.sportbuddy.grpc.UsageOrBuilder> 
        getUsageFieldBuilder() {
      if (usageBuilder_ == null) {
        usageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sportbuddy.grpc.Usage, com.sportbuddy.grpc.Usage.Builder, com.sportbuddy.grpc.UsageOrBuilder>(
                getUsage(),
                getParentForChildren(),
                isClean());
        usage_ = null;
      }
      return usageBuilder_;
    }

    private com.sportbuddy.grpc.ModelInfo modelInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sportbuddy.grpc.ModelInfo, com.sportbuddy.grpc.ModelInfo.Builder, com.sportbuddy.grpc.ModelInfoOrBuilder> modelInfoBuilder_;
    /**
     * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
     * @return Whether the modelInfo field is set.
     */
    public boolean hasModelInfo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
     * @return The modelInfo.
     */
    public com.sportbuddy.grpc.ModelInfo getModelInfo() {
      if (modelInfoBuilder_ == null) {
        return modelInfo_ == null ? com.sportbuddy.grpc.ModelInfo.getDefaultInstance() : modelInfo_;
      } else {
        return modelInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
     */
    public Builder setModelInfo(com.sportbuddy.grpc.ModelInfo value) {
      if (modelInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modelInfo_ = value;
      } else {
        modelInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
     */
    public Builder setModelInfo(
        com.sportbuddy.grpc.ModelInfo.Builder builderForValue) {
      if (modelInfoBuilder_ == null) {
        modelInfo_ = builderForValue.build();
      } else {
        modelInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
     */
    public Builder mergeModelInfo(com.sportbuddy.grpc.ModelInfo value) {
      if (modelInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          modelInfo_ != null &&
          modelInfo_ != com.sportbuddy.grpc.ModelInfo.getDefaultInstance()) {
          getModelInfoBuilder().mergeFrom(value);
        } else {
          modelInfo_ = value;
        }
      } else {
        modelInfoBuilder_.mergeFrom(value);
      }
      if (modelInfo_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
     */
    public Builder clearModelInfo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      modelInfo_ = null;
      if (modelInfoBuilder_ != null) {
        modelInfoBuilder_.dispose();
        modelInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
     */
    public com.sportbuddy.grpc.ModelInfo.Builder getModelInfoBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getModelInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
     */
    public com.sportbuddy.grpc.ModelInfoOrBuilder getModelInfoOrBuilder() {
      if (modelInfoBuilder_ != null) {
        return modelInfoBuilder_.getMessageOrBuilder();
      } else {
        return modelInfo_ == null ?
            com.sportbuddy.grpc.ModelInfo.getDefaultInstance() : modelInfo_;
      }
    }
    /**
     * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sportbuddy.grpc.ModelInfo, com.sportbuddy.grpc.ModelInfo.Builder, com.sportbuddy.grpc.ModelInfoOrBuilder> 
        getModelInfoFieldBuilder() {
      if (modelInfoBuilder_ == null) {
        modelInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sportbuddy.grpc.ModelInfo, com.sportbuddy.grpc.ModelInfo.Builder, com.sportbuddy.grpc.ModelInfoOrBuilder>(
                getModelInfo(),
                getParentForChildren(),
                isClean());
        modelInfo_ = null;
      }
      return modelInfoBuilder_;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gigachat.v1.ChatResponse)
  }

  // @@protoc_insertion_point(class_scope:gigachat.v1.ChatResponse)
  private static final com.sportbuddy.grpc.ChatResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sportbuddy.grpc.ChatResponse();
  }

  public static com.sportbuddy.grpc.ChatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatResponse>
      PARSER = new com.google.protobuf.AbstractParser<ChatResponse>() {
    @java.lang.Override
    public ChatResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sportbuddy.grpc.ChatResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

