// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

/**
 * Protobuf type {@code gigachat.v1.ChatOptions}
 */
public final class ChatOptions extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gigachat.v1.ChatOptions)
    ChatOptionsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatOptions.newBuilder() to construct.
  private ChatOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatOptions() {
    flags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatOptions();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_ChatOptions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_ChatOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sportbuddy.grpc.ChatOptions.class, com.sportbuddy.grpc.ChatOptions.Builder.class);
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 1;
  private float temperature_ = 0F;
  /**
   * <code>float temperature = 1;</code>
   * @return The temperature.
   */
  @java.lang.Override
  public float getTemperature() {
    return temperature_;
  }

  public static final int TOP_P_FIELD_NUMBER = 2;
  private float topP_ = 0F;
  /**
   * <code>float top_p = 2;</code>
   * @return The topP.
   */
  @java.lang.Override
  public float getTopP() {
    return topP_;
  }

  public static final int MAX_ALTERNATIVES_FIELD_NUMBER = 3;
  private int maxAlternatives_ = 0;
  /**
   * <code>int32 max_alternatives = 3;</code>
   * @return The maxAlternatives.
   */
  @java.lang.Override
  public int getMaxAlternatives() {
    return maxAlternatives_;
  }

  public static final int MAX_TOKENS_FIELD_NUMBER = 4;
  private int maxTokens_ = 0;
  /**
   * <code>int32 max_tokens = 4;</code>
   * @return The maxTokens.
   */
  @java.lang.Override
  public int getMaxTokens() {
    return maxTokens_;
  }

  public static final int REPETITION_PENALTY_FIELD_NUMBER = 5;
  private float repetitionPenalty_ = 0F;
  /**
   * <code>float repetition_penalty = 5;</code>
   * @return The repetitionPenalty.
   */
  @java.lang.Override
  public float getRepetitionPenalty() {
    return repetitionPenalty_;
  }

  public static final int UPDATE_INTERVAL_FIELD_NUMBER = 6;
  private float updateInterval_ = 0F;
  /**
   * <code>float update_interval = 6;</code>
   * @return The updateInterval.
   */
  @java.lang.Override
  public float getUpdateInterval() {
    return updateInterval_;
  }

  public static final int FLAGS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList flags_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string flags = 7;</code>
   * @return A list containing the flags.
   */
  public com.google.protobuf.ProtocolStringList
      getFlagsList() {
    return flags_;
  }
  /**
   * <code>repeated string flags = 7;</code>
   * @return The count of flags.
   */
  public int getFlagsCount() {
    return flags_.size();
  }
  /**
   * <code>repeated string flags = 7;</code>
   * @param index The index of the element to return.
   * @return The flags at the given index.
   */
  public java.lang.String getFlags(int index) {
    return flags_.get(index);
  }
  /**
   * <code>repeated string flags = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the flags at the given index.
   */
  public com.google.protobuf.ByteString
      getFlagsBytes(int index) {
    return flags_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
      output.writeFloat(1, temperature_);
    }
    if (java.lang.Float.floatToRawIntBits(topP_) != 0) {
      output.writeFloat(2, topP_);
    }
    if (maxAlternatives_ != 0) {
      output.writeInt32(3, maxAlternatives_);
    }
    if (maxTokens_ != 0) {
      output.writeInt32(4, maxTokens_);
    }
    if (java.lang.Float.floatToRawIntBits(repetitionPenalty_) != 0) {
      output.writeFloat(5, repetitionPenalty_);
    }
    if (java.lang.Float.floatToRawIntBits(updateInterval_) != 0) {
      output.writeFloat(6, updateInterval_);
    }
    for (int i = 0; i < flags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, flags_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, temperature_);
    }
    if (java.lang.Float.floatToRawIntBits(topP_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, topP_);
    }
    if (maxAlternatives_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, maxAlternatives_);
    }
    if (maxTokens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, maxTokens_);
    }
    if (java.lang.Float.floatToRawIntBits(repetitionPenalty_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, repetitionPenalty_);
    }
    if (java.lang.Float.floatToRawIntBits(updateInterval_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, updateInterval_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < flags_.size(); i++) {
        dataSize += computeStringSizeNoTag(flags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFlagsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sportbuddy.grpc.ChatOptions)) {
      return super.equals(obj);
    }
    com.sportbuddy.grpc.ChatOptions other = (com.sportbuddy.grpc.ChatOptions) obj;

    if (java.lang.Float.floatToIntBits(getTemperature())
        != java.lang.Float.floatToIntBits(
            other.getTemperature())) return false;
    if (java.lang.Float.floatToIntBits(getTopP())
        != java.lang.Float.floatToIntBits(
            other.getTopP())) return false;
    if (getMaxAlternatives()
        != other.getMaxAlternatives()) return false;
    if (getMaxTokens()
        != other.getMaxTokens()) return false;
    if (java.lang.Float.floatToIntBits(getRepetitionPenalty())
        != java.lang.Float.floatToIntBits(
            other.getRepetitionPenalty())) return false;
    if (java.lang.Float.floatToIntBits(getUpdateInterval())
        != java.lang.Float.floatToIntBits(
            other.getUpdateInterval())) return false;
    if (!getFlagsList()
        .equals(other.getFlagsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTemperature());
    hash = (37 * hash) + TOP_P_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTopP());
    hash = (37 * hash) + MAX_ALTERNATIVES_FIELD_NUMBER;
    hash = (53 * hash) + getMaxAlternatives();
    hash = (37 * hash) + MAX_TOKENS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxTokens();
    hash = (37 * hash) + REPETITION_PENALTY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRepetitionPenalty());
    hash = (37 * hash) + UPDATE_INTERVAL_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getUpdateInterval());
    if (getFlagsCount() > 0) {
      hash = (37 * hash) + FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + getFlagsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sportbuddy.grpc.ChatOptions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.ChatOptions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.ChatOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.ChatOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.ChatOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.ChatOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.ChatOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sportbuddy.grpc.ChatOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sportbuddy.grpc.ChatOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sportbuddy.grpc.ChatOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sportbuddy.grpc.ChatOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sportbuddy.grpc.ChatOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sportbuddy.grpc.ChatOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gigachat.v1.ChatOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gigachat.v1.ChatOptions)
      com.sportbuddy.grpc.ChatOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_ChatOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_ChatOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sportbuddy.grpc.ChatOptions.class, com.sportbuddy.grpc.ChatOptions.Builder.class);
    }

    // Construct using com.sportbuddy.grpc.ChatOptions.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      temperature_ = 0F;
      topP_ = 0F;
      maxAlternatives_ = 0;
      maxTokens_ = 0;
      repetitionPenalty_ = 0F;
      updateInterval_ = 0F;
      flags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_ChatOptions_descriptor;
    }

    @java.lang.Override
    public com.sportbuddy.grpc.ChatOptions getDefaultInstanceForType() {
      return com.sportbuddy.grpc.ChatOptions.getDefaultInstance();
    }

    @java.lang.Override
    public com.sportbuddy.grpc.ChatOptions build() {
      com.sportbuddy.grpc.ChatOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sportbuddy.grpc.ChatOptions buildPartial() {
      com.sportbuddy.grpc.ChatOptions result = new com.sportbuddy.grpc.ChatOptions(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sportbuddy.grpc.ChatOptions result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.temperature_ = temperature_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.topP_ = topP_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.maxAlternatives_ = maxAlternatives_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.maxTokens_ = maxTokens_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.repetitionPenalty_ = repetitionPenalty_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.updateInterval_ = updateInterval_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        flags_.makeImmutable();
        result.flags_ = flags_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sportbuddy.grpc.ChatOptions) {
        return mergeFrom((com.sportbuddy.grpc.ChatOptions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sportbuddy.grpc.ChatOptions other) {
      if (other == com.sportbuddy.grpc.ChatOptions.getDefaultInstance()) return this;
      if (other.getTemperature() != 0F) {
        setTemperature(other.getTemperature());
      }
      if (other.getTopP() != 0F) {
        setTopP(other.getTopP());
      }
      if (other.getMaxAlternatives() != 0) {
        setMaxAlternatives(other.getMaxAlternatives());
      }
      if (other.getMaxTokens() != 0) {
        setMaxTokens(other.getMaxTokens());
      }
      if (other.getRepetitionPenalty() != 0F) {
        setRepetitionPenalty(other.getRepetitionPenalty());
      }
      if (other.getUpdateInterval() != 0F) {
        setUpdateInterval(other.getUpdateInterval());
      }
      if (!other.flags_.isEmpty()) {
        if (flags_.isEmpty()) {
          flags_ = other.flags_;
          bitField0_ |= 0x00000040;
        } else {
          ensureFlagsIsMutable();
          flags_.addAll(other.flags_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              temperature_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 21: {
              topP_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 24: {
              maxAlternatives_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              maxTokens_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 45: {
              repetitionPenalty_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 45
            case 53: {
              updateInterval_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 53
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFlagsIsMutable();
              flags_.add(s);
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float temperature_ ;
    /**
     * <code>float temperature = 1;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public float getTemperature() {
      return temperature_;
    }
    /**
     * <code>float temperature = 1;</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(float value) {

      temperature_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float temperature = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      bitField0_ = (bitField0_ & ~0x00000001);
      temperature_ = 0F;
      onChanged();
      return this;
    }

    private float topP_ ;
    /**
     * <code>float top_p = 2;</code>
     * @return The topP.
     */
    @java.lang.Override
    public float getTopP() {
      return topP_;
    }
    /**
     * <code>float top_p = 2;</code>
     * @param value The topP to set.
     * @return This builder for chaining.
     */
    public Builder setTopP(float value) {

      topP_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float top_p = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopP() {
      bitField0_ = (bitField0_ & ~0x00000002);
      topP_ = 0F;
      onChanged();
      return this;
    }

    private int maxAlternatives_ ;
    /**
     * <code>int32 max_alternatives = 3;</code>
     * @return The maxAlternatives.
     */
    @java.lang.Override
    public int getMaxAlternatives() {
      return maxAlternatives_;
    }
    /**
     * <code>int32 max_alternatives = 3;</code>
     * @param value The maxAlternatives to set.
     * @return This builder for chaining.
     */
    public Builder setMaxAlternatives(int value) {

      maxAlternatives_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_alternatives = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxAlternatives() {
      bitField0_ = (bitField0_ & ~0x00000004);
      maxAlternatives_ = 0;
      onChanged();
      return this;
    }

    private int maxTokens_ ;
    /**
     * <code>int32 max_tokens = 4;</code>
     * @return The maxTokens.
     */
    @java.lang.Override
    public int getMaxTokens() {
      return maxTokens_;
    }
    /**
     * <code>int32 max_tokens = 4;</code>
     * @param value The maxTokens to set.
     * @return This builder for chaining.
     */
    public Builder setMaxTokens(int value) {

      maxTokens_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_tokens = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxTokens() {
      bitField0_ = (bitField0_ & ~0x00000008);
      maxTokens_ = 0;
      onChanged();
      return this;
    }

    private float repetitionPenalty_ ;
    /**
     * <code>float repetition_penalty = 5;</code>
     * @return The repetitionPenalty.
     */
    @java.lang.Override
    public float getRepetitionPenalty() {
      return repetitionPenalty_;
    }
    /**
     * <code>float repetition_penalty = 5;</code>
     * @param value The repetitionPenalty to set.
     * @return This builder for chaining.
     */
    public Builder setRepetitionPenalty(float value) {

      repetitionPenalty_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>float repetition_penalty = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepetitionPenalty() {
      bitField0_ = (bitField0_ & ~0x00000010);
      repetitionPenalty_ = 0F;
      onChanged();
      return this;
    }

    private float updateInterval_ ;
    /**
     * <code>float update_interval = 6;</code>
     * @return The updateInterval.
     */
    @java.lang.Override
    public float getUpdateInterval() {
      return updateInterval_;
    }
    /**
     * <code>float update_interval = 6;</code>
     * @param value The updateInterval to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateInterval(float value) {

      updateInterval_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>float update_interval = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateInterval() {
      bitField0_ = (bitField0_ & ~0x00000020);
      updateInterval_ = 0F;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList flags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFlagsIsMutable() {
      if (!flags_.isModifiable()) {
        flags_ = new com.google.protobuf.LazyStringArrayList(flags_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <code>repeated string flags = 7;</code>
     * @return A list containing the flags.
     */
    public com.google.protobuf.ProtocolStringList
        getFlagsList() {
      flags_.makeImmutable();
      return flags_;
    }
    /**
     * <code>repeated string flags = 7;</code>
     * @return The count of flags.
     */
    public int getFlagsCount() {
      return flags_.size();
    }
    /**
     * <code>repeated string flags = 7;</code>
     * @param index The index of the element to return.
     * @return The flags at the given index.
     */
    public java.lang.String getFlags(int index) {
      return flags_.get(index);
    }
    /**
     * <code>repeated string flags = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the flags at the given index.
     */
    public com.google.protobuf.ByteString
        getFlagsBytes(int index) {
      return flags_.getByteString(index);
    }
    /**
     * <code>repeated string flags = 7;</code>
     * @param index The index to set the value at.
     * @param value The flags to set.
     * @return This builder for chaining.
     */
    public Builder setFlags(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFlagsIsMutable();
      flags_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string flags = 7;</code>
     * @param value The flags to add.
     * @return This builder for chaining.
     */
    public Builder addFlags(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFlagsIsMutable();
      flags_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string flags = 7;</code>
     * @param values The flags to add.
     * @return This builder for chaining.
     */
    public Builder addAllFlags(
        java.lang.Iterable<java.lang.String> values) {
      ensureFlagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, flags_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string flags = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlags() {
      flags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string flags = 7;</code>
     * @param value The bytes of the flags to add.
     * @return This builder for chaining.
     */
    public Builder addFlagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFlagsIsMutable();
      flags_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gigachat.v1.ChatOptions)
  }

  // @@protoc_insertion_point(class_scope:gigachat.v1.ChatOptions)
  private static final com.sportbuddy.grpc.ChatOptions DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sportbuddy.grpc.ChatOptions();
  }

  public static com.sportbuddy.grpc.ChatOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatOptions>
      PARSER = new com.google.protobuf.AbstractParser<ChatOptions>() {
    @java.lang.Override
    public ChatOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatOptions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatOptions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sportbuddy.grpc.ChatOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

