// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public interface ChatOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gigachat.v1.ChatOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float temperature = 1;</code>
   * @return The temperature.
   */
  float getTemperature();

  /**
   * <code>float top_p = 2;</code>
   * @return The topP.
   */
  float getTopP();

  /**
   * <code>int32 max_alternatives = 3;</code>
   * @return The maxAlternatives.
   */
  int getMaxAlternatives();

  /**
   * <code>int32 max_tokens = 4;</code>
   * @return The maxTokens.
   */
  int getMaxTokens();

  /**
   * <code>float repetition_penalty = 5;</code>
   * @return The repetitionPenalty.
   */
  float getRepetitionPenalty();

  /**
   * <code>float update_interval = 6;</code>
   * @return The updateInterval.
   */
  float getUpdateInterval();

  /**
   * <code>repeated string flags = 7;</code>
   * @return A list containing the flags.
   */
  java.util.List<java.lang.String>
      getFlagsList();
  /**
   * <code>repeated string flags = 7;</code>
   * @return The count of flags.
   */
  int getFlagsCount();
  /**
   * <code>repeated string flags = 7;</code>
   * @param index The index of the element to return.
   * @return The flags at the given index.
   */
  java.lang.String getFlags(int index);
  /**
   * <code>repeated string flags = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the flags at the given index.
   */
  com.google.protobuf.ByteString
      getFlagsBytes(int index);
}
