// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public interface ChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gigachat.v1.ChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
   */
  java.util.List<com.sportbuddy.grpc.Alternative> 
      getAlternativesList();
  /**
   * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
   */
  com.sportbuddy.grpc.Alternative getAlternatives(int index);
  /**
   * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
   */
  int getAlternativesCount();
  /**
   * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
   */
  java.util.List<? extends com.sportbuddy.grpc.AlternativeOrBuilder> 
      getAlternativesOrBuilderList();
  /**
   * <code>repeated .gigachat.v1.Alternative alternatives = 1;</code>
   */
  com.sportbuddy.grpc.AlternativeOrBuilder getAlternativesOrBuilder(
      int index);

  /**
   * <code>.gigachat.v1.Usage usage = 2;</code>
   * @return Whether the usage field is set.
   */
  boolean hasUsage();
  /**
   * <code>.gigachat.v1.Usage usage = 2;</code>
   * @return The usage.
   */
  com.sportbuddy.grpc.Usage getUsage();
  /**
   * <code>.gigachat.v1.Usage usage = 2;</code>
   */
  com.sportbuddy.grpc.UsageOrBuilder getUsageOrBuilder();

  /**
   * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
   * @return Whether the modelInfo field is set.
   */
  boolean hasModelInfo();
  /**
   * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
   * @return The modelInfo.
   */
  com.sportbuddy.grpc.ModelInfo getModelInfo();
  /**
   * <code>.gigachat.v1.ModelInfo model_info = 3;</code>
   */
  com.sportbuddy.grpc.ModelInfoOrBuilder getModelInfoOrBuilder();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
