// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public interface ChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gigachat.v1.ChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gigachat.v1.ChatOptions options = 1;</code>
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <code>.gigachat.v1.ChatOptions options = 1;</code>
   * @return The options.
   */
  com.sportbuddy.grpc.ChatOptions getOptions();
  /**
   * <code>.gigachat.v1.ChatOptions options = 1;</code>
   */
  com.sportbuddy.grpc.ChatOptionsOrBuilder getOptionsOrBuilder();

  /**
   * <code>string model = 2;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 2;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>repeated .gigachat.v1.Message messages = 3;</code>
   */
  java.util.List<com.sportbuddy.grpc.Message> 
      getMessagesList();
  /**
   * <code>repeated .gigachat.v1.Message messages = 3;</code>
   */
  com.sportbuddy.grpc.Message getMessages(int index);
  /**
   * <code>repeated .gigachat.v1.Message messages = 3;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .gigachat.v1.Message messages = 3;</code>
   */
  java.util.List<? extends com.sportbuddy.grpc.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .gigachat.v1.Message messages = 3;</code>
   */
  com.sportbuddy.grpc.MessageOrBuilder getMessagesOrBuilder(
      int index);
}
