// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public final class GigaChatProto {
  private GigaChatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_ChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_ChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_ChatOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_ChatOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_ChatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_ChatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_Alternative_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_Alternative_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_Usage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_Usage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_ModelInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_ModelInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_ListModelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_ListModelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_ListModelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_ListModelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_Model_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_Model_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_RetrieveModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_RetrieveModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gigachat_v1_RetrieveModelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gigachat_v1_RetrieveModelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016gigachat.proto\022\013gigachat.v1\"o\n\013ChatReq" +
      "uest\022)\n\007options\030\001 \001(\0132\030.gigachat.v1.Chat" +
      "Options\022\r\n\005model\030\002 \001(\t\022&\n\010messages\030\003 \003(\013" +
      "2\024.gigachat.v1.Message\"\243\001\n\013ChatOptions\022\023" +
      "\n\013temperature\030\001 \001(\002\022\r\n\005top_p\030\002 \001(\002\022\030\n\020ma" +
      "x_alternatives\030\003 \001(\005\022\022\n\nmax_tokens\030\004 \001(\005" +
      "\022\032\n\022repetition_penalty\030\005 \001(\002\022\027\n\017update_i" +
      "nterval\030\006 \001(\002\022\r\n\005flags\030\007 \003(\t\"E\n\007Message\022" +
      "\014\n\004role\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\022\033\n\023unproc" +
      "essed_content\030\003 \001(\t\"\240\001\n\014ChatResponse\022.\n\014" +
      "alternatives\030\001 \003(\0132\030.gigachat.v1.Alterna" +
      "tive\022!\n\005usage\030\002 \001(\0132\022.gigachat.v1.Usage\022" +
      "*\n\nmodel_info\030\003 \001(\0132\026.gigachat.v1.ModelI" +
      "nfo\022\021\n\ttimestamp\030\004 \001(\003\"Z\n\013Alternative\022%\n" +
      "\007message\030\001 \001(\0132\024.gigachat.v1.Message\022\025\n\r" +
      "finish_reason\030\002 \001(\t\022\r\n\005index\030\003 \001(\005\"O\n\005Us" +
      "age\022\025\n\rprompt_tokens\030\001 \001(\005\022\031\n\021completion" +
      "_tokens\030\002 \001(\005\022\024\n\014total_tokens\030\003 \001(\005\"*\n\tM" +
      "odelInfo\022\014\n\004name\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\"" +
      "\023\n\021ListModelsRequest\"8\n\022ListModelsRespon" +
      "se\022\"\n\006models\030\001 \003(\0132\022.gigachat.v1.Model\"7" +
      "\n\005Model\022\014\n\004name\030\001 \001(\t\022\016\n\006object\030\002 \001(\t\022\020\n" +
      "\010owned_by\030\003 \001(\t\"$\n\024RetrieveModelRequest\022" +
      "\014\n\004name\030\001 \001(\t\":\n\025RetrieveModelResponse\022!" +
      "\n\005model\030\001 \001(\0132\022.gigachat.v1.Model2\217\001\n\013Ch" +
      "atService\022;\n\004Chat\022\030.gigachat.v1.ChatRequ" +
      "est\032\031.gigachat.v1.ChatResponse\022C\n\nChatSt" +
      "ream\022\030.gigachat.v1.ChatRequest\032\031.gigacha" +
      "t.v1.ChatResponse0\0012\266\001\n\rModelsService\022M\n" +
      "\nListModels\022\036.gigachat.v1.ListModelsRequ" +
      "est\032\037.gigachat.v1.ListModelsResponse\022V\n\r" +
      "RetrieveModel\022!.gigachat.v1.RetrieveMode" +
      "lRequest\032\".gigachat.v1.RetrieveModelResp" +
      "onseB3\n\023com.sportbuddy.grpcB\rGigaChatPro" +
      "toP\001Z\013./;protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gigachat_v1_ChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gigachat_v1_ChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_ChatRequest_descriptor,
        new java.lang.String[] { "Options", "Model", "Messages", });
    internal_static_gigachat_v1_ChatOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gigachat_v1_ChatOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_ChatOptions_descriptor,
        new java.lang.String[] { "Temperature", "TopP", "MaxAlternatives", "MaxTokens", "RepetitionPenalty", "UpdateInterval", "Flags", });
    internal_static_gigachat_v1_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gigachat_v1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_Message_descriptor,
        new java.lang.String[] { "Role", "Content", "UnprocessedContent", });
    internal_static_gigachat_v1_ChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gigachat_v1_ChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_ChatResponse_descriptor,
        new java.lang.String[] { "Alternatives", "Usage", "ModelInfo", "Timestamp", });
    internal_static_gigachat_v1_Alternative_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gigachat_v1_Alternative_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_Alternative_descriptor,
        new java.lang.String[] { "Message", "FinishReason", "Index", });
    internal_static_gigachat_v1_Usage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_gigachat_v1_Usage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_Usage_descriptor,
        new java.lang.String[] { "PromptTokens", "CompletionTokens", "TotalTokens", });
    internal_static_gigachat_v1_ModelInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_gigachat_v1_ModelInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_ModelInfo_descriptor,
        new java.lang.String[] { "Name", "Version", });
    internal_static_gigachat_v1_ListModelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_gigachat_v1_ListModelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_ListModelsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_gigachat_v1_ListModelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_gigachat_v1_ListModelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_ListModelsResponse_descriptor,
        new java.lang.String[] { "Models", });
    internal_static_gigachat_v1_Model_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_gigachat_v1_Model_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_Model_descriptor,
        new java.lang.String[] { "Name", "Object", "OwnedBy", });
    internal_static_gigachat_v1_RetrieveModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_gigachat_v1_RetrieveModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_RetrieveModelRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_gigachat_v1_RetrieveModelResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_gigachat_v1_RetrieveModelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gigachat_v1_RetrieveModelResponse_descriptor,
        new java.lang.String[] { "Model", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
