// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public interface ListModelsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gigachat.v1.ListModelsRequest)
    com.google.protobuf.MessageOrBuilder {
}
