// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public interface ListModelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gigachat.v1.ListModelsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .gigachat.v1.Model models = 1;</code>
   */
  java.util.List<com.sportbuddy.grpc.Model> 
      getModelsList();
  /**
   * <code>repeated .gigachat.v1.Model models = 1;</code>
   */
  com.sportbuddy.grpc.Model getModels(int index);
  /**
   * <code>repeated .gigachat.v1.Model models = 1;</code>
   */
  int getModelsCount();
  /**
   * <code>repeated .gigachat.v1.Model models = 1;</code>
   */
  java.util.List<? extends com.sportbuddy.grpc.ModelOrBuilder> 
      getModelsOrBuilderList();
  /**
   * <code>repeated .gigachat.v1.Model models = 1;</code>
   */
  com.sportbuddy.grpc.ModelOrBuilder getModelsOrBuilder(
      int index);
}
