// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gigachat.v1.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string role = 1;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 1;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string unprocessed_content = 3;</code>
   * @return The unprocessedContent.
   */
  java.lang.String getUnprocessedContent();
  /**
   * <code>string unprocessed_content = 3;</code>
   * @return The bytes for unprocessedContent.
   */
  com.google.protobuf.ByteString
      getUnprocessedContentBytes();
}
