// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public interface ModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gigachat.v1.Model)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string object = 2;</code>
   * @return The object.
   */
  java.lang.String getObject();
  /**
   * <code>string object = 2;</code>
   * @return The bytes for object.
   */
  com.google.protobuf.ByteString
      getObjectBytes();

  /**
   * <code>string owned_by = 3;</code>
   * @return The ownedBy.
   */
  java.lang.String getOwnedBy();
  /**
   * <code>string owned_by = 3;</code>
   * @return The bytes for ownedBy.
   */
  com.google.protobuf.ByteString
      getOwnedByBytes();
}
