// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public interface RetrieveModelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gigachat.v1.RetrieveModelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gigachat.v1.Model model = 1;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>.gigachat.v1.Model model = 1;</code>
   * @return The model.
   */
  com.sportbuddy.grpc.Model getModel();
  /**
   * <code>.gigachat.v1.Model model = 1;</code>
   */
  com.sportbuddy.grpc.ModelOrBuilder getModelOrBuilder();
}
