// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

/**
 * Protobuf type {@code gigachat.v1.Usage}
 */
public final class Usage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gigachat.v1.Usage)
    UsageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Usage.newBuilder() to construct.
  private Usage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Usage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Usage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_Usage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_Usage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sportbuddy.grpc.Usage.class, com.sportbuddy.grpc.Usage.Builder.class);
  }

  public static final int PROMPT_TOKENS_FIELD_NUMBER = 1;
  private int promptTokens_ = 0;
  /**
   * <code>int32 prompt_tokens = 1;</code>
   * @return The promptTokens.
   */
  @java.lang.Override
  public int getPromptTokens() {
    return promptTokens_;
  }

  public static final int COMPLETION_TOKENS_FIELD_NUMBER = 2;
  private int completionTokens_ = 0;
  /**
   * <code>int32 completion_tokens = 2;</code>
   * @return The completionTokens.
   */
  @java.lang.Override
  public int getCompletionTokens() {
    return completionTokens_;
  }

  public static final int TOTAL_TOKENS_FIELD_NUMBER = 3;
  private int totalTokens_ = 0;
  /**
   * <code>int32 total_tokens = 3;</code>
   * @return The totalTokens.
   */
  @java.lang.Override
  public int getTotalTokens() {
    return totalTokens_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (promptTokens_ != 0) {
      output.writeInt32(1, promptTokens_);
    }
    if (completionTokens_ != 0) {
      output.writeInt32(2, completionTokens_);
    }
    if (totalTokens_ != 0) {
      output.writeInt32(3, totalTokens_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (promptTokens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, promptTokens_);
    }
    if (completionTokens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, completionTokens_);
    }
    if (totalTokens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalTokens_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sportbuddy.grpc.Usage)) {
      return super.equals(obj);
    }
    com.sportbuddy.grpc.Usage other = (com.sportbuddy.grpc.Usage) obj;

    if (getPromptTokens()
        != other.getPromptTokens()) return false;
    if (getCompletionTokens()
        != other.getCompletionTokens()) return false;
    if (getTotalTokens()
        != other.getTotalTokens()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROMPT_TOKENS_FIELD_NUMBER;
    hash = (53 * hash) + getPromptTokens();
    hash = (37 * hash) + COMPLETION_TOKENS_FIELD_NUMBER;
    hash = (53 * hash) + getCompletionTokens();
    hash = (37 * hash) + TOTAL_TOKENS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalTokens();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sportbuddy.grpc.Usage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.Usage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.Usage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.Usage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.Usage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sportbuddy.grpc.Usage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sportbuddy.grpc.Usage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sportbuddy.grpc.Usage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sportbuddy.grpc.Usage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sportbuddy.grpc.Usage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sportbuddy.grpc.Usage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sportbuddy.grpc.Usage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sportbuddy.grpc.Usage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gigachat.v1.Usage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gigachat.v1.Usage)
      com.sportbuddy.grpc.UsageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_Usage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_Usage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sportbuddy.grpc.Usage.class, com.sportbuddy.grpc.Usage.Builder.class);
    }

    // Construct using com.sportbuddy.grpc.Usage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      promptTokens_ = 0;
      completionTokens_ = 0;
      totalTokens_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sportbuddy.grpc.GigaChatProto.internal_static_gigachat_v1_Usage_descriptor;
    }

    @java.lang.Override
    public com.sportbuddy.grpc.Usage getDefaultInstanceForType() {
      return com.sportbuddy.grpc.Usage.getDefaultInstance();
    }

    @java.lang.Override
    public com.sportbuddy.grpc.Usage build() {
      com.sportbuddy.grpc.Usage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sportbuddy.grpc.Usage buildPartial() {
      com.sportbuddy.grpc.Usage result = new com.sportbuddy.grpc.Usage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sportbuddy.grpc.Usage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.promptTokens_ = promptTokens_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.completionTokens_ = completionTokens_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalTokens_ = totalTokens_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sportbuddy.grpc.Usage) {
        return mergeFrom((com.sportbuddy.grpc.Usage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sportbuddy.grpc.Usage other) {
      if (other == com.sportbuddy.grpc.Usage.getDefaultInstance()) return this;
      if (other.getPromptTokens() != 0) {
        setPromptTokens(other.getPromptTokens());
      }
      if (other.getCompletionTokens() != 0) {
        setCompletionTokens(other.getCompletionTokens());
      }
      if (other.getTotalTokens() != 0) {
        setTotalTokens(other.getTotalTokens());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              promptTokens_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              completionTokens_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              totalTokens_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int promptTokens_ ;
    /**
     * <code>int32 prompt_tokens = 1;</code>
     * @return The promptTokens.
     */
    @java.lang.Override
    public int getPromptTokens() {
      return promptTokens_;
    }
    /**
     * <code>int32 prompt_tokens = 1;</code>
     * @param value The promptTokens to set.
     * @return This builder for chaining.
     */
    public Builder setPromptTokens(int value) {

      promptTokens_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 prompt_tokens = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPromptTokens() {
      bitField0_ = (bitField0_ & ~0x00000001);
      promptTokens_ = 0;
      onChanged();
      return this;
    }

    private int completionTokens_ ;
    /**
     * <code>int32 completion_tokens = 2;</code>
     * @return The completionTokens.
     */
    @java.lang.Override
    public int getCompletionTokens() {
      return completionTokens_;
    }
    /**
     * <code>int32 completion_tokens = 2;</code>
     * @param value The completionTokens to set.
     * @return This builder for chaining.
     */
    public Builder setCompletionTokens(int value) {

      completionTokens_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 completion_tokens = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompletionTokens() {
      bitField0_ = (bitField0_ & ~0x00000002);
      completionTokens_ = 0;
      onChanged();
      return this;
    }

    private int totalTokens_ ;
    /**
     * <code>int32 total_tokens = 3;</code>
     * @return The totalTokens.
     */
    @java.lang.Override
    public int getTotalTokens() {
      return totalTokens_;
    }
    /**
     * <code>int32 total_tokens = 3;</code>
     * @param value The totalTokens to set.
     * @return This builder for chaining.
     */
    public Builder setTotalTokens(int value) {

      totalTokens_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_tokens = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalTokens() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalTokens_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gigachat.v1.Usage)
  }

  // @@protoc_insertion_point(class_scope:gigachat.v1.Usage)
  private static final com.sportbuddy.grpc.Usage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sportbuddy.grpc.Usage();
  }

  public static com.sportbuddy.grpc.Usage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Usage>
      PARSER = new com.google.protobuf.AbstractParser<Usage>() {
    @java.lang.Override
    public Usage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Usage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Usage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sportbuddy.grpc.Usage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

