// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gigachat.proto

// Protobuf Java Version: 3.25.3
package com.sportbuddy.grpc;

public interface UsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gigachat.v1.Usage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 prompt_tokens = 1;</code>
   * @return The promptTokens.
   */
  int getPromptTokens();

  /**
   * <code>int32 completion_tokens = 2;</code>
   * @return The completionTokens.
   */
  int getCompletionTokens();

  /**
   * <code>int32 total_tokens = 3;</code>
   * @return The totalTokens.
   */
  int getTotalTokens();
}
